name: Create Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: チェックアウトリポジトリ
        uses: actions/checkout@v2

      - name: .NET セットアップ
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'

      - name: 依存関係の復元
        run: dotnet restore

      - name: ビルド
        run: dotnet build --configuration Release

      - name: パブリッシュ
        run: dotnet publish --configuration Release

      - name: リリース用アーティファクトの作成
        run: |
          mkdir release
          cp -r ./DDic/bin/Release/net8.0-windows/* ./release/
          cp README.md ./release/
          cp LICENSE ./release/
          cp -r ./image ./release/image
          cd release
          zip -r ../DDic.zip ./*
        shell: bash

      - name: リリースの作成
        uses: softprops/action-gh-release@v1
        with:
          files: DDic.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
